#!/bin/sh
set -e

echo "Running pre-commit fixes..."

cljfmt fix

TARGET_DIR="yappinator/"

FILES=$(git diff --cached --name-only --diff-filter=ACM | \
  grep -E "^${TARGET_DIR}.*\.(clj|cljs|edn)$" || true)

[ -z "$FILES" ] && exit 0

for file in $FILES; do
  [ -f "$file" ] || continue
  
  # Ensure exactly one newline at EOF
  sed -i '' -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$file"
  echo "" >> "$file"
done

git add $FILES

clj-kondo --lint yappinator/src yappinator/test

echo "Pre-commit checks passed!"
exit 0
