FROM node:23-alpine

WORKDIR /app

RUN apk add --no-cache openjdk17-jre-headless

COPY yappinator .

RUN npm install

RUN npx shadow-cljs release app

EXPOSE 4000

CMD ["npx", "shadow-cljs", "server"]
