name: Backend Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java (OpenJDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Clojure CLI
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest

      - name: Cache Clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-deps-${{ hashFiles('backend/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Run backend tests
        run: clojure -X:test
