name: Frontend Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: yappinator

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
  
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: npm install

      - run: npx shadow-cljs release test

      - run: node out/test.js